import { stoichAt, stoichIndex, type Stoich } from "./letters";

export type KinKind = "kin" | "eris";

export interface Hora {
  letter: Stoich;
  index: number;
  watch: "night" | "day";
  noun: string;
  greek: string;
  realm: string;
  cult: string;
  myth: string;
  gift: string;
  shadow: string;
  invitation: string;
  kin: Stoich[];
  eris: Stoich[];
}

const FACES: Omit<Hora, "letter" | "index">[] = [
  {
    watch: "night",
    noun: "Hekate",
    greek: "Ἑκάτη",
    realm: "the three-way threshold",
    cult: "Enodia · keys · the new-moon leftovers",
    myth: "You stand where roads split and no one owns the dark yet.",
    gift: "You can hold a key without pretending you built the door.",
    shadow: "You collect crossroads and never choose one.",
    invitation: "Name the road you will actually walk after sunset.",
    kin: ["Ε", "Λ", "Μ"],
    eris: ["Π", "Υ", "Ν"],
  },
  {
    watch: "night",
    noun: "Persephone",
    greek: "Περσεφόνη",
    realm: "the descent",
    cult: "Kore · Eleusis · the pomegranate",
    myth: "You know both rooms: the green one and the one under it.",
    gift: "You can go down and still come back with a season.",
    shadow: "You make every leaving a death so no one can ask you to stay.",
    invitation: "Bring one living thing with you into the dark.",
    kin: ["Ψ", "Η", "Θ"],
    eris: ["Ρ", "Ξ", "Γ"],
  },
  {
    watch: "night",
    noun: "Hypnos",
    greek: "Ὕπνος",
    realm: "the unargued rest",
    cult: "brother of Death · poppy · Lethe’s bank",
    myth: "You stop the day without killing it.",
    gift: "People can put the work down near you.",
    shadow: "You sleep through the hour that required you.",
    invitation: "Rest as a craft, not as an escape.",
    kin: ["Δ", "Μ", "Η"],
    eris: ["Ι", "Τ", "Π"],
  },
  {
    watch: "night",
    noun: "Nyx",
    greek: "Νύξ",
    realm: "the first dark",
    cult: "older than the Olympians · the egg · the veil",
    myth: "Before the names of day, you were already a country.",
    gift: "You can begin a world without lighting it yet.",
    shadow: "You refuse every dawn as a betrayal.",
    invitation: "Let one thing become visible without losing the dark that made it.",
    kin: ["Γ", "Κ", "Α"],
    eris: ["Ι", "Ν", "Υ"],
  },
  {
    watch: "night",
    noun: "Hermes Chthonios",
    greek: "Ἑρμῆς Χθόνιος",
    realm: "the psychopomp road",
    cult: "guide of souls · herm · the coin",
    myth: "You walk messages into rooms the living will not enter.",
    gift: "You can speak across a boundary without pretending there is none.",
    shadow: "You become only a courier and forget you have a name.",
    invitation: "Carry one true word into a place that has none.",
    kin: ["Ξ", "Α", "Μ"],
    eris: ["Ν", "Φ", "Τ"],
  },
  {
    watch: "night",
    noun: "the Erinyes",
    greek: "Ἐρινύες",
    realm: "the unpaid blood",
    cult: "Furies · Eumenides · the sworn night",
    myth: "You remember what the day has agreed to forget.",
    gift: "An injustice cannot finish itself in your company.",
    shadow: "You hunt past the point of repair.",
    invitation: "Name the debt, then name what would actually settle it.",
    kin: ["Κ", "Θ", "Ι"],
    eris: ["Σ", "Ν", "Ο"],
  },
  {
    watch: "night",
    noun: "Asklepios",
    greek: "Ἀσκληπιός",
    realm: "the incubation",
    cult: "Epidaurus · snake · the dream that heals",
    myth: "You let the body speak while the will is asleep.",
    gift: "Repair that does not require a performance.",
    shadow: "You treat every wound as a shrine and never leave the temple.",
    invitation: "Heal one thing that is not a story about you.",
    kin: ["Γ", "Β", "Λ"],
    eris: ["Τ", "Ο", "Ζ"],
  },
  {
    watch: "night",
    noun: "Dionysos Nyktelios",
    greek: "Διόνυσος Νυκτέλιος",
    realm: "the night festival",
    cult: "the twice-born · the mask · the wet god",
    myth: "You unmake a rigid self so a living one can drink.",
    gift: "Joy that is not purchased by numbness.",
    shadow: "You smash the cup and call the shards liberation.",
    invitation: "Loosen one law that was only fear. Keep one law that is love.",
    kin: ["Β", "Ο", "Π"],
    eris: ["Σ", "Ν", "Ι"],
  },
  {
    watch: "night",
    noun: "Themis",
    greek: "Θέμις",
    realm: "the assembled right",
    cult: "divine law · the assembly · the unwritten custom",
    myth: "You know what is due before anyone writes it down.",
    gift: "A room becomes fairer when you enter it.",
    shadow: "You freeze a living custom into a weapon.",
    invitation: "Ask what is due — not what is usual.",
    kin: ["Κ", "Υ", "Σ"],
    eris: ["Λ", "Θ", "Τ"],
  },
  {
    watch: "night",
    noun: "Nemesis",
    greek: "Νέμεσις",
    realm: "the measured return",
    cult: "retribution · the cubit · the leveled pile",
    myth: "What exceeds its portion is brought back to size.",
    gift: "You can see inflation of the self before it becomes a war.",
    shadow: "You enjoy the fall more than the balance.",
    invitation: "Restore a portion. Do not enjoy the cut.",
    kin: ["Ι", "Ζ", "Υ"],
    eris: ["Ο", "Λ", "Θ"],
  },
  {
    watch: "night",
    noun: "Tyche",
    greek: "Τύχη",
    realm: "the city’s luck",
    cult: "Fortune · the mural crown · the rudder",
    myth: "You steer what no one planned and still call it a city.",
    gift: "You can receive a turn of luck without claiming you earned the gods.",
    shadow: "You gamble other people’s lives and call it fate.",
    invitation: "Take the tiller for one hour. Do not worship the wind.",
    kin: ["Α", "Η", "Χ"],
    eris: ["Ι", "Κ", "Ν"],
  },
  {
    watch: "night",
    noun: "Thanatos",
    greek: "Θάνατος",
    realm: "the last door",
    cult: "gentle Death · twin of Sleep · the inverted torch",
    myth: "You end a thing without cruelty and without theatre.",
    gift: "You can close what is finished.",
    shadow: "You close what was only tired.",
    invitation: "Name the one thing that is already over. Let it be over.",
    kin: ["Γ", "Α", "Ε"],
    eris: ["Π", "Ν", "Η"],
  },
  {
    watch: "day",
    noun: "Hestia",
    greek: "Ἑστία",
    realm: "the hearth",
    cult: "first and last offering · the unmoving fire",
    myth: "You keep a center that does not travel, so others can.",
    gift: "A day can begin because something stayed lit.",
    shadow: "You refuse every road and call the ashes home.",
    invitation: "Feed the fire. Then let someone else sit near it.",
    kin: ["Ξ", "Φ", "Υ"],
    eris: ["Α", "Ε", "Μ"],
  },
  {
    watch: "day",
    noun: "Hermes",
    greek: "Ἑρμῆς",
    realm: "the road and the market",
    cult: "herald · thief · the herm at the gate",
    myth: "You move meaning from one mouth to another before it spoils.",
    gift: "A closed room becomes a conversation.",
    shadow: "You trade so fast nothing is true for more than a minute.",
    invitation: "Carry one message that is not an advertisement.",
    kin: ["Ε", "Ο", "Ν"],
    eris: ["Β", "Ι", "Ψ"],
  },
  {
    watch: "day",
    noun: "Aphrodite",
    greek: "Ἀφροδίτη",
    realm: "the foam and the binding",
    cult: "Ourania and Pandemos · the girdle · Cyprus",
    myth: "You make two things want to remain two and still touch.",
    gift: "Desire that does not have to become ownership.",
    shadow: "You use beauty as a net and then complain it holds.",
    invitation: "Want one thing that can want you back.",
    kin: ["Η", "Ρ", "Π"],
    eris: ["Ρ", "Σ", "Ζ"],
  },
  {
    watch: "day",
    noun: "Apollo",
    greek: "Ἀπόλλων",
    realm: "the measured light",
    cult: "Delphi · the lyre · the far-striker",
    myth: "You strike at a distance and still have to live with the song.",
    gift: "Clarity that does not have to shout.",
    shadow: "You purify until nothing living remains.",
    invitation: "Tell the true thing. Leave room for the body that hears it.",
    kin: ["Ι", "Θ", "Ρ"],
    eris: ["Θ", "Α", "Τ"],
  },
  {
    watch: "day",
    noun: "Artemis",
    greek: "Ἄρτεμις",
    realm: "the wild margin",
    cult: "Potnia Theron · the uncut grove · childbirth’s edge",
    myth: "You protect what has not yet been named by the city.",
    gift: "A life can stay itself in your company.",
    shadow: "You shoot anyone who comes near, including the ones who were invited.",
    invitation: "Guard one wild thing. Let one guest approach.",
    kin: ["Ο", "Π", "Ψ"],
    eris: ["Ο", "Τ", "Ξ"],
  },
  {
    watch: "day",
    noun: "Athena",
    greek: "Ἀθηνᾶ",
    realm: "the clever city",
    cult: "Polias · the olive · the unmothered mind",
    myth: "You think in the middle of the fight and still weave after it.",
    gift: "Strategy that is not merely cruelty with a map.",
    shadow: "You become only a helmet and forget the olive.",
    invitation: "Win one thing without humiliating the room.",
    kin: ["Ι", "Υ", "Τ"],
    eris: ["Τ", "Ο", "Θ"],
  },
  {
    watch: "day",
    noun: "Ares",
    greek: "Ἄρης",
    realm: "the open strife",
    cult: "the spear · the shout · the necessary heat",
    myth: "You go forward when delay has become a lie.",
    gift: "Courage that does not need an audience.",
    shadow: "You start wars because peace feels like death.",
    invitation: "Fight the thing that is actually on you. Put the rest down.",
    kin: ["Ο", "Σ", "Χ"],
    eris: ["Σ", "Π", "Ν"],
  },
  {
    watch: "day",
    noun: "Zeus",
    greek: "Ζεύς",
    realm: "the high weather",
    cult: "Xenios · the oak · the stranger’s right",
    myth: "You hold the sky so the guest can eat underneath it.",
    gift: "A law that still knows how to welcome.",
    shadow: "You become the storm and call it justice.",
    invitation: "Keep one promise to a stranger. Keep one promise to yourself.",
    kin: ["Φ", "Ν", "Κ"],
    eris: ["Ω", "Α", "Δ"],
  },
  {
    watch: "day",
    noun: "Hera",
    greek: "Ἥρα",
    realm: "the vowed bond",
    cult: "the cow-eyed · the marriage · the long fidelity",
    myth: "You take a vow seriously enough to suffer it.",
    gift: "A bond that is not a mood.",
    shadow: "You punish the vow instead of repairing it.",
    invitation: "Keep what you chose. Release what you only trapped.",
    kin: ["Υ", "Ν", "Ο"],
    eris: ["Ξ", "Θ", "Ε"],
  },
  {
    watch: "day",
    noun: "Poseidon",
    greek: "Ποσειδῶν",
    realm: "the shaken floor",
    cult: "the trident · horses · the unquiet sea",
    myth: "You move the ground when the city has forgotten it stands on anything.",
    gift: "Force that can also be a road (the sea is a road).",
    shadow: "You wreck harbors because stillness offends you.",
    invitation: "Shake one false foundation. Do not flood the house.",
    kin: ["Λ", "Τ", "Ψ"],
    eris: ["Ν", "Σ", "Ι"],
  },
  {
    watch: "day",
    noun: "Demeter",
    greek: "Δημήτηρ",
    realm: "the grain and the grief",
    cult: "Eleusis · the ear of wheat · the mother’s search",
    myth: "You feed the city and you will stop the world if the child is taken.",
    gift: "Sustenance that remembers who it is for.",
    shadow: "You starve the field to prove you were wronged.",
    invitation: "Feed what is living. Mourn what is gone. Do not confuse them.",
    kin: ["Β", "Ρ", "Χ"],
    eris: ["Ξ", "Μ", "Τ"],
  },
  {
    watch: "day",
    noun: "Hephaistos",
    greek: "Ἥφαιστος",
    realm: "the forge",
    cult: "the lame god · the net · the made thing",
    myth: "You make what the beautiful gods only wear.",
    gift: "Work that remains when the feast is over.",
    shadow: "You trap love in a net and then live in the trap.",
    invitation: "Finish one made thing. Let it leave the shop.",
    kin: ["Χ", "Ν", "Σ"],
    eris: ["Υ", "Ο", "Π"],
  },
];

export const HORAE: Hora[] = FACES.map((face, index) => ({
  ...face,
  letter: stoichAt(index),
  index,
}));

export function horaOf(letter: Stoich): Hora {
  return HORAE[stoichIndex(letter)] ?? HORAE[0]!;
}

export function kinOf(letter: Stoich): Stoich[] {
  return horaOf(letter).kin;
}

export function erisOf(letter: Stoich): Stoich[] {
  return horaOf(letter).eris;
}
