import type { House, Letter } from "./types";

/**
 * Twenty-six houses. A house is a role, not a personality.
 * Pearson / Campbell / tarot are likenesses — correspondences, not creeds.
 */
export const HOUSES: Record<Letter, House> = {
  A: {
    letter: "A",
    noun: "Seeker",
    house: "House of the Seeker",
    tradition: "Pearson Seeker · Campbell's departure",
    myth: "The first step is already a leaving. What is wanted has not yet been named, but the door has.",
    element: "air",
  },
  B: {
    letter: "B",
    noun: "Caregiver",
    house: "House of the Caregiver",
    tradition: "Pearson Caregiver · the Hearth",
    myth: "Someone must keep the fire. Belonging is a craft, not a feeling.",
    element: "earth",
  },
  C: {
    letter: "C",
    noun: "Rebel",
    house: "House of the Rebel",
    tradition: "Pearson Destroyer · the Spark",
    myth: "A dead rule is not made holy by age. The match is struck so a truer room can be built.",
    element: "fire",
  },
  D: {
    letter: "D",
    noun: "Hermit",
    house: "House of the Hermit",
    tradition: "The lantern · IX of the tarot",
    myth: "What is not yet clear must be stayed with. The practice is the announcement.",
    element: "earth",
  },
  E: {
    letter: "E",
    noun: "Explorer",
    house: "House of the Explorer",
    tradition: "Pearson Explorer · the open map",
    myth: "There is more room than the last life used. A cage that is familiar is still a cage.",
    element: "air",
  },
  F: {
    letter: "F",
    noun: "Fool",
    house: "House of the Fool",
    tradition: "Tarot 0 · beginner's mind",
    myth: "The unnumbered card. Freedom here is attention that has not been owned.",
    element: "aether",
  },
  G: {
    letter: "G",
    noun: "Creator",
    house: "House of the Creator",
    tradition: "Pearson Creator · the grove",
    myth: "What is tended grows. Increase with roots, not merely more stuff.",
    element: "earth",
  },
  H: {
    letter: "H",
    noun: "Prophet",
    house: "House of the Prophet",
    tradition: "The far word · hospitality of truth",
    myth: "Hope with a backbone, and a door left open for the one who is not yet ready.",
    element: "fire",
  },
  I: {
    letter: "I",
    noun: "Sage",
    house: "House of the Sage",
    tradition: "Pearson Sage · the inner room",
    myth: "Insight before applause. A life whose inside and outside are asked to match.",
    element: "air",
  },
  J: {
    letter: "J",
    noun: "Hero",
    house: "House of the Hero",
    tradition: "Campbell's return · motion with a conscience",
    myth: "A crossing that intends to come home. Joy that does not look away.",
    element: "fire",
  },
  K: {
    letter: "K",
    noun: "Orphan",
    house: "House of the Orphan",
    tradition: "Pearson Orphan · chosen kinship",
    myth: "Belonging as a craft. The spare chair is the sacrament.",
    element: "water",
  },
  L: {
    letter: "L",
    noun: "Lover",
    house: "House of the Lover",
    tradition: "Pearson Lover · leadership as warmth",
    myth: "Love as the willingness to go first in warmth, and to stay after the first shine fades.",
    element: "water",
  },
  M: {
    letter: "M",
    noun: "Warrior",
    house: "House of the Warrior",
    tradition: "Pearson Warrior · the clean fight",
    myth: "The practice that has begun to carry itself. Movement toward mastery, not mere activity.",
    element: "fire",
  },
  N: {
    letter: "N",
    noun: "Healer",
    house: "House of the Healer",
    tradition: "The garden · notice before repair",
    myth: "Notice before you fix. Care without talking down. Feed what is already alive.",
    element: "water",
  },
  O: {
    letter: "O",
    noun: "Priestess",
    house: "House of the Priestess",
    tradition: "The High Priestess · a circle that admits a guest",
    myth: "Origin and opportunity in one breath. Order that can still open.",
    element: "water",
  },
  P: {
    letter: "P",
    noun: "Ruler",
    house: "House of the Ruler",
    tradition: "Pearson Ruler · aimed presence",
    myth: "Presence with a direction. Potential carved into a sequence of kept days.",
    element: "earth",
  },
  Q: {
    letter: "Q",
    noun: "Mystic",
    house: "House of the Mystic",
    tradition: "The question · quintessence",
    myth: "A real question is worth more than a crowded answer. The essential thing, and the rest left.",
    element: "aether",
  },
  R: {
    letter: "R",
    noun: "Bard",
    house: "House of the Bard",
    tradition: "The true note · oral memory",
    myth: "A people remember themselves by a sound they can enter. Restore the pitch.",
    element: "air",
  },
  S: {
    letter: "S",
    noun: "Weaver",
    house: "House of the Weaver",
    tradition: "Synergy · the living braid",
    myth: "Strength that comes from things being more together than apart — if a name remains.",
    element: "earth",
  },
  T: {
    letter: "T",
    noun: "Alchemist",
    house: "House of the Alchemist",
    tradition: "Death and the work · necessary fire",
    myth: "Truth that costs something. The old skin is shed so a new shape can live.",
    element: "fire",
  },
  U: {
    letter: "U",
    noun: "Peacemaker",
    house: "House of the Peacemaker",
    tradition: "Pearson Lover/Ruler hinge · the bowl",
    myth: "Unity that includes the unique. A we that does not require a smaller I.",
    element: "water",
  },
  V: {
    letter: "V",
    noun: "Oracle",
    house: "House of the Oracle",
    tradition: "Vocation · a picture you can walk toward",
    myth: "A life seen while it is still only an idea — and then one ordinary step that belongs to it.",
    element: "aether",
  },
  W: {
    letter: "W",
    noun: "Innocent",
    house: "House of the Innocent",
    tradition: "Pearson Innocent · first light",
    myth: "Wonder is wisdom before it hardens into advice. Look again.",
    element: "air",
  },
  X: {
    letter: "X",
    noun: "Trickster",
    house: "House of the Trickster",
    tradition: "The rare variable · the crossing",
    myth: "The life that will not stay inside a rule that has started to lie. Crossing, not exile as a brand.",
    element: "aether",
  },
  Y: {
    letter: "Y",
    noun: "Shapeshifter",
    house: "House of the Shapeshifter",
    tradition: "The living hinge · yes and not-yet",
    myth: "A self that can turn without breaking. Yielding that has learned a spine.",
    element: "water",
  },
  Z: {
    letter: "Z",
    noun: "Magician",
    house: "House of the Magician",
    tradition: "Tarot I · will clean enough to use",
    myth: "Intensity without waste. The peak is a place to visit. Come down.",
    element: "fire",
  },
};

export function houseOf(letter: Letter): House {
  return HOUSES[letter] ?? HOUSES.X;
}
