import type { Letter, LetterTheme, TensionPair } from "./types";

export const LEXICON: Record<Letter, LetterTheme> = {
  A: {
    letter: "A",
    name: "Aspiration",
    keywords: ["ambition", "authenticity", "awakening", "abundance"],
    essence: "A is the Seeker's letter. It starts things. It names what you want to become.",
    inner: "Inwardly, A is a private hunger for a truer life — not louder, more itself.",
    outer: "Outwardly, A leans forward: it starts things, names them, and asks the room to rise.",
    gift: "You meet the world as a beginning. Wanting, in you, is honesty.",
    challenge: "Wanting without choosing becomes restlessness. Pick one thing and keep it.",
    invitation: "Notice where you already want out, and take the step.",
    complements: ["D", "N", "G"],
  },
  B: {
    letter: "B",
    name: "Binding",
    keywords: ["balance", "belonging", "bravery", "beauty"],
    essence: "B is the Caregiver's letter. It holds. It gathers what would scatter and makes a home.",
    inner: "Inwardly, B wants a center that can be trusted — balance that is real, not performed.",
    outer: "Outwardly, B makes circles: friendships, rooms, loyalties, the quiet courage of staying.",
    gift: "You make people and ideas belong to one another.",
    challenge: "Holding can become trapping. Belong without disappearing.",
    invitation: "Ask what is worth keeping — and what needs to be released.",
    complements: ["C", "F", "X"],
  },
  C: {
    letter: "C",
    name: "Catalysis",
    keywords: ["curiosity", "courage", "creation", "change"],
    essence: "C is the Rebel's letter. It will not leave a stuck room stuck. It starts the reaction.",
    inner: "Inwardly, C needs to turn the object over and see the other side.",
    outer: "Outwardly, C starts conversations, projects, departures, the first honest sentence.",
    gift: "You are often the reason something begins that would not have begun without you.",
    challenge: "Change without patience can burn the thing it meant to wake up.",
    invitation: "Start one change worth keeping, and stay long enough to see what it becomes.",
    complements: ["B", "R", "D"],
  },
  D: {
    letter: "D",
    name: "Depth",
    keywords: ["discipline", "determination", "discernment", "devotion"],
    essence: "D is the Hermit's letter. It prefers the practice to the announcement.",
    inner: "Inwardly, D stays with what is not clear yet.",
    outer: "Outwardly, D shows as craft, loyalty, and the unfashionable work of finishing.",
    gift: "You give things time. What you devote yourself to, you change.",
    challenge: "Depth can become hiding. Bring something back to the surface.",
    invitation: "Let one practice be visible.",
    complements: ["E", "F", "L"],
  },
  E: {
    letter: "E",
    name: "Expansion",
    keywords: ["empathy", "evolution", "energy", "emergence"],
    essence: "E is the Explorer's letter. It says there is more room than you were using.",
    inner: "Inwardly, E widens feeling so other people can share it.",
    outer: "Outwardly, E reaches: new people, new work, the next version of a life already in motion.",
    gift: "You make more space than the situation asked for — and someone usually needs it.",
    challenge: "Expansion without a shoreline becomes scatter. Growth still needs a shape.",
    invitation: "Grow in one direction, not in every direction at once.",
    complements: ["D", "P", "S"],
  },
  F: {
    letter: "F",
    name: "Freedom",
    keywords: ["focus", "faith", "flow", "fidelity"],
    essence: "F is the Fool's letter. Freedom here is not escape. It is attention that has not been owned.",
    inner: "Inwardly, F protects the right to move as you actually need to move.",
    outer: "Outwardly, F shows as independence, clean focus, and a refusal to be owned by noise.",
    gift: "You keep room around a life. Other people breathe easier near it.",
    challenge: "Freedom without a promise is only drift. Choose, then stay freely.",
    invitation: "Ask what you would still choose if no one were watching — then give it your focus.",
    complements: ["B", "D", "P"],
  },
  G: {
    letter: "G",
    name: "Growth",
    keywords: ["gratitude", "grace", "grounding", "generosity"],
    essence: "G is the Creator's letter. What is tended grows. This is growth with roots, not just more stuff.",
    inner: "Inwardly, G is patient becoming. Gratitude is how the next self stands.",
    outer: "Outwardly, G gives. It grounds rooms, feeds work, and makes increase look like courtesy.",
    gift: "You leave people and projects larger than you found them, without making a speech of it.",
    challenge: "Growth that never rests becomes exhaustion. Rest is part of the work.",
    invitation: "Tend one living thing — a craft, a friendship, a practice.",
    complements: ["X", "Z", "N"],
  },
  H: {
    letter: "H",
    name: "Horizon",
    keywords: ["harmony", "honesty", "hope", "hospitality"],
    essence: "H is the Prophet's letter. Hope with a backbone, and a door left open.",
    inner: "Inwardly, H keeps faith with a farther self. Honesty is the compass.",
    outer: "Outwardly, H hosts: it makes a room in which other people can tell the truth.",
    gift: "You hold a longer view, and offer it without forcing anyone to share it.",
    challenge: "Looking far can neglect the person standing next to you.",
    invitation: "Keep the long view, and set one honest table today.",
    complements: ["I", "K", "P"],
  },
  I: {
    letter: "I",
    name: "Illumination",
    keywords: ["insight", "integrity", "imagination", "interiority"],
    essence: "I is the Sage's letter. Insight before applause.",
    inner: "Inwardly, I is a well-lit room that not everyone is invited into. Imagination lives there first.",
    outer: "Outwardly, I appears as integrity: a life whose inside and outside match.",
    gift: "You see the pattern before it is fashionable, and you keep faith with what you see.",
    challenge: "The inner room can lock. Insight is meant to reach a shared table.",
    invitation: "Say one private insight out loud.",
    complements: ["S", "U", "H"],
  },
  J: {
    letter: "J",
    name: "Journey",
    keywords: ["joy", "justice", "judgment", "juxtaposition"],
    essence: "J is the Hero's letter. Motion with a conscience. Joy that does not look away.",
    inner: "Inwardly, J compares, weighs, and will not rest in a false peace.",
    outer: "Outwardly, J travels, argues, celebrates, and puts unlikely things beside each other until they make sense.",
    gift: "You move a life — your own or someone else's — from here to a more honest there.",
    challenge: "The journey can become a refusal to arrive. Judgment needs a place to set the pack down.",
    invitation: "Take the next honest mile. Let joy come along.",
    complements: ["K", "O", "S"],
  },
  K: {
    letter: "K",
    name: "Kinship",
    keywords: ["knowledge", "kindness", "key", "kinship"],
    essence: "K is the Orphan's letter. Knowledge that wants to be useful to someone specific. Belonging as a craft.",
    inner: "Inwardly, K understands by standing with people.",
    outer: "Outwardly, K knits family and chosen family.",
    gift: "You remember, you open, you make knowledge feel like kindness.",
    challenge: "Kinship can become a closed room. The key is also for the stranger who knocks.",
    invitation: "Offer one precise kindness to someone who already has a claim on you — then one who does not.",
    complements: ["J", "H", "Q"],
  },
  L: {
    letter: "L",
    name: "Luminosity",
    keywords: ["love", "light", "leadership", "loyalty"],
    essence: "L is the Lover's letter. Love as leadership: the willingness to go first in warmth.",
    inner: "Inwardly, L is loyalty to what — and whom — has already been loved.",
    outer: "Outwardly, L clarifies a room. People find their edges in your light, and sometimes their courage.",
    gift: "You make the better thing visible, and stay with it after the first shine fades.",
    challenge: "Brightness can hide fatigue. Love that leads must also rest.",
    invitation: "Give your attention to one true thing.",
    complements: ["D", "I", "W"],
  },
  M: {
    letter: "M",
    name: "Momentum",
    keywords: ["mindfulness", "mystery", "mastery", "movement"],
    essence: "M is the Warrior's letter. The practice that has begun to carry itself.",
    inner: "Inwardly, M holds both mystery and method — attention that does not flatten what it studies.",
    outer: "Outwardly, M is work with a pulse: movement toward mastery, not just activity.",
    gift: "You get things moving and keep them moving until they have a life of their own.",
    challenge: "Speed can outrun meaning. Pause without losing the current.",
    invitation: "Choose the motion that is already true, and give it a daily return.",
    complements: ["N", "Q", "F"],
  },
  N: {
    letter: "N",
    name: "Nurture",
    keywords: ["novelty", "nobility", "noticing", "nourishment"],
    essence: "N is the Healer's letter. Notice before you fix. Care without talking down.",
    inner: "Inwardly, N pays attention to what is young, tender, or not yet named.",
    outer: "Outwardly, N feeds people, ideas, rooms — the unglamorous work of keeping life workable.",
    gift: "You see what needs feeding while others are still arguing about the problem.",
    challenge: "Nurture can forget the nurturer. Newness for its own sake can abandon what was just starting.",
    invitation: "Feed what is already alive in you. That is maintenance, not vanity.",
    complements: ["A", "M", "Q"],
  },
  O: {
    letter: "O",
    name: "Opening",
    keywords: ["openness", "order", "opportunity", "origin"],
    essence: "O is the Priestess's letter. Origin and opportunity in the same breath. A circle that does not close against the world.",
    inner: "Inwardly, O is a willingness to be revised. Openness as a discipline, not a mood.",
    outer: "Outwardly, O makes order that can still admit a guest, a chance, a second beginning.",
    gift: "You leave a door unlatched in systems that prefer locks.",
    challenge: "Opening without order becomes a draft. Opportunity needs a frame, or it will not stay.",
    invitation: "Open one true door, and give the room behind it a simple, kept order.",
    complements: ["D", "P", "Q"],
  },
  P: {
    letter: "P",
    name: "Purpose",
    keywords: ["passion", "patience", "presence", "potential"],
    essence: "P is the Ruler's letter. Presence with a direction. Aimed work, and the patience to carve it.",
    inner: "Inwardly, P is heat that wants a worthy object — passion that has agreed to wait.",
    outer: "Outwardly, P aims. It turns potential into a sequence of kept days.",
    gift: "You give scattered energy a spine. People remember what they were for, near you.",
    challenge: "Purpose can harden into a script. Potential is larger than any single aim.",
    invitation: "Name the work that would still matter if it were slower. Then do the next inch of it.",
    complements: ["F", "E", "Y"],
  },
  Q: {
    letter: "Q",
    name: "Quest",
    keywords: ["quiet", "quality", "questioning", "quintessence"],
    essence: "Q is the Mystic's letter. It prefers a real question to a crowded answer.",
    inner: "Inwardly, Q wants the essential thing and will leave the rest.",
    outer: "Outwardly, Q goes looking. It will cross a desert for a better question.",
    gift: "You refuse the cheap version. Your standards are a form of love.",
    challenge: "The quest can despise the ordinary day. Quiet is not the same as leaving the living.",
    invitation: "Ask the one question that would change the week, and stay beside it.",
    complements: ["N", "K", "M"],
  },
  R: {
    letter: "R",
    name: "Resonance",
    keywords: ["resilience", "reflection", "rhythm", "reverence"],
    essence: "R is the Bard's letter. It answers a sound with a truer one.",
    inner: "Inwardly, R listens until the signal is clean.",
    outer: "Outwardly, R keeps rhythm: returning, recovering, making a life that can be danced as well as endured.",
    gift: "You restore pitch — in a conversation, a team, a day that had gone sharp.",
    challenge: "Resonance can become mere echo. Resilience is not the same as never changing key.",
    invitation: "Listen for the note that is yours, and return to it once before the day is over.",
    complements: ["C", "T", "W"],
  },
  S: {
    letter: "S",
    name: "Synergy",
    keywords: ["strength", "serenity", "sincerity", "synthesis"],
    essence: "S is the Weaver's letter. Strength that comes from things being more together than apart.",
    inner: "Inwardly, S wants a calm honesty that does not need to raise its voice.",
    outer: "Outwardly, S composes people, ideas, efforts — the quiet architecture of we.",
    gift: "You make combinations no single part could have invented.",
    challenge: "Synergy can dissolve the self into the braid. Keep a name that is still yours.",
    invitation: "Join what wants joining, and keep one thread of your own.",
    complements: ["I", "E", "U"],
  },
  T: {
    letter: "T",
    name: "Transformation",
    keywords: ["truth", "trust", "tension", "transcendence"],
    essence: "T is the Alchemist's letter. Truth that costs something. Tension that makes a new shape possible.",
    inner: "Inwardly, T will not live in a story that has expired. Trust comes after the old skin is shed.",
    outer: "Outwardly, T marks thresholds: the hard conversation, the changed work, the life that no longer fits.",
    gift: "You midwife necessary change — not by force, but by refusing the comfortable lie.",
    challenge: "Transformation can become a habit of crisis. Some truths want tending, not another fire.",
    invitation: "Name the one thing that is already over. Cross with as much tenderness as courage.",
    complements: ["B", "R", "Y"],
  },
  U: {
    letter: "U",
    name: "Unity",
    keywords: ["understanding", "uniqueness", "unfolding", "uprightness"],
    essence: "U is the Peacemaker's letter. It holds difference without erasing it. Unity here includes the unique.",
    inner: "Inwardly, U unfolds toward wholeness. Uprightness is a spine, not a pose.",
    outer: "Outwardly, U reconciles. It looks for the understanding that lets two true things stand together.",
    gift: "You make a we that does not require anyone to become a smaller I.",
    challenge: "Unity can paper over a needed conflict. Understanding is not the same as agreement at any cost.",
    invitation: "Hold the whole, and keep one unique edge of yourself unblended.",
    complements: ["I", "S", "X"],
  },
  V: {
    letter: "V",
    name: "Vision",
    keywords: ["vitality", "virtue", "vulnerability", "vocation"],
    essence: "V is the Oracle's letter. A picture of a life with enough life in it that you can walk toward it.",
    inner: "Inwardly, V is a vivid picture of a life worth the risk of being seen.",
    outer: "Outwardly, V points. It names a direction with enough energy that others can walk toward it.",
    gift: "You see the shape of a future while it is still only an idea, and you say so.",
    challenge: "Vision can refuse the humble near. Vulnerability keeps vocation from becoming a statue.",
    invitation: "Tell the true picture, then take one ordinary step that belongs to it.",
    complements: ["D", "P", "W"],
  },
  W: {
    letter: "W",
    name: "Wonder",
    keywords: ["wisdom", "will", "witness", "weaving"],
    essence: "W is the Innocent's letter. Wonder is wisdom before it hardens into advice.",
    inner: "Inwardly, W stays available to being changed by what it sees.",
    outer: "Outwardly, W connects strands, and is willing to be present without fixing.",
    gift: "You restore astonishment — a rare and practical mercy.",
    challenge: "Wonder can float above the will to act. Witnessing is not always enough.",
    invitation: "Look again at something you think you already understand. Then make one new connection.",
    complements: ["D", "L", "R"],
  },
  X: {
    letter: "X",
    name: "Edge",
    keywords: ["the rare", "the extreme", "the crossing", "the unknown"],
    essence: "X is the Trickster's letter. The rare choice, the unknown variable, the life that will not stay inside a rule that has started to lie.",
    inner: "Inwardly, X keeps a private wilderness — a refusal to be fully mapped.",
    outer: "Outwardly, X appears as the unusual choice, the sharp talent, the place you do not resemble the family pattern.",
    gift: "You bring the missing variable. Rooms become more honest when you arrive.",
    challenge: "The edge can become exile as a habit. Crossing is a journey, not a permanent address.",
    invitation: "Honor what is rare in you, and let it serve something that is not only yourself.",
    complements: ["B", "G", "U"],
  },
  Y: {
    letter: "Y",
    name: "Yielding",
    keywords: ["yearning", "youth", "yes", "the flexible axis"],
    essence: "Y is the Shapeshifter's letter. Yearning that has learned yes — and not-yet.",
    inner: "Inwardly, Y is a living hinge: a self that can turn without breaking.",
    outer: "Outwardly, Y adapts, consents, redirects. Flexibility becomes a form of intelligence.",
    gift: "You keep options humane. You know how to say yes without becoming a door anyone may walk through.",
    challenge: "Yielding can postpone a necessary stand. Yearning needs a chosen direction.",
    invitation: "Bend where bending is wisdom. Then let one yes become a spine.",
    complements: ["A", "P", "Z"],
  },
  Z: {
    letter: "Z",
    name: "Zenith",
    keywords: ["zeal", "zen", "final intensity", "the pure peak"],
    essence: "Z is the Magician's letter. Intensity without waste. Will clean enough to use.",
    inner: "Inwardly, Z wants the pure version: the finished thought, the undiluted yes.",
    outer: "Outwardly, Z concentrates. It will spend a season on a single height.",
    gift: "You raise the ceiling of a room by refusing the lukewarm.",
    challenge: "The peak is a place to visit. Living only there starves the climb and the descent.",
    invitation: "Give your zeal one worthy summit, and practice coming down.",
    complements: ["Y", "G", "N"],
  },
};

export const TENSIONS: TensionPair[] = [
  {
    a: "A",
    b: "N",
    title: "Aspiration and Nurture",
    copy: "The drive to become meets the duty to tend. Let ambition feed what is already alive, instead of dropping it for a shinier summit.",
  },
  {
    a: "A",
    b: "Y",
    title: "Aspiration and Yielding",
    copy: "You live in the argument between striving and surrender. Both sides are useful if neither is exiled.",
  },
  {
    a: "B",
    b: "C",
    title: "Binding and Catalysis",
    copy: "The wish to hold meets the wish to change. Know when a bond is a home and when it is a lid.",
  },
  {
    a: "B",
    b: "F",
    title: "Binding and Freedom",
    copy: "You want a door that latches and a window that opens. Both are honest.",
  },
  {
    a: "B",
    b: "T",
    title: "Binding and Transformation",
    copy: "What you keep and what you must drop speak at once. Some loyalties can finish their season without that being a betrayal.",
  },
  {
    a: "B",
    b: "X",
    title: "Binding and Edge",
    copy: "You may feel most yourself slightly outside the very rooms you help to make.",
  },
  {
    a: "C",
    b: "R",
    title: "Catalysis and Resonance",
    copy: "You start reactions and you also hear when the tone has gone wrong. Use both: ignite, then tune.",
  },
  {
    a: "D",
    b: "E",
    title: "Depth and Expansion",
    copy: "You want both the long stay and the larger room. Grow from a root, not from a rumor.",
  },
  {
    a: "D",
    b: "F",
    title: "Depth and Freedom",
    copy: "Practice makes you free. Freedom must not dissolve the practice.",
  },
  {
    a: "D",
    b: "O",
    title: "Depth and Opening",
    copy: "You can go far in and still leave a door open. Let order serve openness, not replace it.",
  },
  {
    a: "D",
    b: "V",
    title: "Depth and Vision",
    copy: "Vision without depth is a poster. Depth without vision is a cellar. You carry both.",
  },
  {
    a: "D",
    b: "W",
    title: "Depth and Wonder",
    copy: "Do not let mastery make you unimpressible, or wonder keep you from the unglamorous hour.",
  },
  {
    a: "D",
    b: "L",
    title: "Depth and Luminosity",
    copy: "You are asked to go down and to shine. Bring something back.",
  },
  {
    a: "F",
    b: "P",
    title: "Freedom and Purpose",
    copy: "Direction need not be a cage, and freedom need not be aimless. You live in that negotiation.",
  },
  {
    a: "G",
    b: "X",
    title: "Growth and Edge",
    copy: "Increase is real in you, and so is the refusal to be only what grows on schedule.",
  },
  {
    a: "H",
    b: "I",
    title: "Horizon and Illumination",
    copy: "Outer hope and inner sight can argue over who leads. Let them take turns.",
  },
  {
    a: "I",
    b: "S",
    title: "Illumination and Synergy",
    copy: "You see alone and you make with others. Neither gift should colonize the other.",
  },
  {
    a: "I",
    b: "U",
    title: "Illumination and Unity",
    copy: "You are asked to belong without dimming the inner room.",
  },
  {
    a: "J",
    b: "K",
    title: "Journey and Kinship",
    copy: "You may feel torn between going and staying. The living answer is often a journey that still writes home.",
  },
  {
    a: "M",
    b: "N",
    title: "Momentum and Nurture",
    copy: "Speed can starve what it carries. Move, and feed the moving thing.",
  },
  {
    a: "N",
    b: "Q",
    title: "Nurture and Quest",
    copy: "Care can postpone the search. The search can neglect the living. Both are your work.",
  },
  {
    a: "Y",
    b: "Z",
    title: "Yielding and Zenith",
    copy: "Flexibility and intensity share this name. Climb, then know how to come down.",
  },
];

export function themeOf(letter: Letter): LetterTheme {
  return LEXICON[letter] ?? LEXICON.X;
}

export function findTension(a: Letter, b: Letter): TensionPair | undefined {
  return TENSIONS.find(
    (t) => (t.a === a && t.b === b) || (t.a === b && t.b === a),
  );
}
